
services:
  pg_db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: msg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 770948
    ports:
      - "5432:5432"
  
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - my-net
  
  pg_admin4:
    container_name: pgadmin
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@user.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadminpwd4"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pg_admin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - my-net
  
  api:
    container_name: www
    build: ./app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - pg_db
      - kafka
    networks:
      - my-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPR_TICK_TIME: 2000
    networks:
      - my-net

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - my-net


 
volumes:
  pg_admin:
  pg:

networks:
  my-net:
    driver: bridge
  broker: